//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesdeLasHorasExtras.EjemploCodigoEspagueti3
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Clase EjemploCodigoEspaguetiModel.Bitacora
    /// </summary>
    public partial class Bitacora
    {
    
    	/// <summary>
    	/// Propiedad edmProperty.
    	/// </summary>
    	/// <value>
    	/// Valor de la propiedad edmProperty.
    	/// </value>
        public int Id { get; set; }
    
    	/// <summary>
    	/// Propiedad edmProperty.
    	/// </summary>
    	/// <value>
    	/// Valor de la propiedad edmProperty.
    	/// </value>
        public string mensaje { get; set; }
    }
}
