//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesdeLasHorasExtras.EjemploCodigoEspagueti3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    /// <summary>
    /// Base de datos de ejemplo de entity framework
    /// </summary>
    /// <seealso cref="System.Data.Entity.DbContext" />
    public partial class EjemploCodigoEspaguetiEntities : DbContext
    {
    	/// <summary>
    	/// Constructor por defecto.
    	/// </summary>
        public EjemploCodigoEspaguetiEntities()
            : base("name=EjemploCodigoEspaguetiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
    }
}
